name: bug or feature requests
description: File a bug or feature requests
body:
- type: textarea
  attributes:
    label: 运行环境
    render: markdown
    description: |
      examples:
        - **OS**: Ubuntu 20.04
        - **PHP**: 8.0.10
        - **wechatpay-php**: 1.3.1
    value: |
        - OS:
        - PHP:
        - wechatpay-php:
  validations:
    required: false

- type: textarea
  attributes:
    label: 描述你的问题现象
    description: |
      报错**贴截图**粘贴或者贴具体信息，提供**必要的代码段**，例如
      代码段:
        ```php
        $instance = \WeChatPay\Builder::factory([]);
        $instance->chain('v2/mmpaymkttransfers/promotion/transfers')->post();
        $instance->v3->smartguide->guides->{'{guide_id}'}->assign->postAsync();
        ```
    placeholder: |
      1. 我在windows10上，PHP7.3环境
      2. 尝试调试xxxxx接口，始终调不通
      3. 我的代代码段如下...
      4. 错误日志如下....
  validations:
    required: false

- type: markdown
  attributes:
    value: |
      如果是接入过程中遇到了业务错误，推荐通过以下任一渠道获取帮助或者反馈问题:
      1. [腾讯客服自助服务专区](https://kf.qq.com/product/wechatpaymentmerchant.html)
      2. [微信支付在线技术支持](https://support.pay.weixin.qq.com/online-service)
      3. [开发者专区](https://developers.weixin.qq.com/community/pay)

      建议正确使用Markdown来描述你的问题，进阶可见[这里](https://guides.github.com/features/mastering-markdown)
