name: CI

on: [push, pull_request]

jobs:
  phpstan:
    name: PHPStan
    strategy:
      fail-fast: false
      matrix:
        php-version: [7.2.5, 7.4]
        os: [ubuntu-latest, macOS-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set git config
        shell: bash
        run: |
          git config --global core.autocrlf false
          git config --global core.symlinks true
        if: runner.os == 'Windows'


      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - uses: actions/checkout@v2

      - name: PHPv${{ matrix.php-version }}-${{ matrix.os }}
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ matrix.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - run: composer phpstan-7
